data:
  processed_path: 'tiny_processed_data'
  word_threshold: 1

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  batch_size: 4
  num_layers: 2
  model_dim: 16
  num_heads: 2
  linear_key_dim: 10
  linear_value_dim: 12
  ffn_dim: 20
  dropout: 0.2

train:
  learning_rate: 0.00001
  optimizer: 'Adam'

  train_steps: 50000
  model_dir: 'logs/check_tiny'

  save_checkpoints_steps: 1000
  check_hook_n_iter: 100
  min_eval_frequency: 100

  print_verbose: True
  debug: False
