data:
  processed_path: 'tiny_processed_data'
  max_seq_length: 20
  word_threshold: 1

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  num_layers: 1
  model_dim: 16
  num_heads: 2
  linear_key_dim: 10
  linear_value_dim: 12
  ffn_dim: 20
  dropout: 0.2

train:
  batch_size: 2
  learning_rate: 0.00001
  train_steps: 50000
  model_dir: 'logs/check_tiny'
  save_checkpoints_steps: 1000
  check_hook_n_iter: 100
  min_eval_frequency: 100

eval:
  batch_size: -1
